services:
  server:
    image: ztancankiri/ghostlink-server:latest
    container_name: ghostlink-server
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ./certs:/app/certs:ro
    environment:
      - NODE_ENV=production
